/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppAppIndexRouteImport } from './routes/_app/app/index'
import { Route as AppAppPlanningRouteImport } from './routes/_app/app/planning'
import { Route as AppAppReportsRouteImport } from './routes/_app/app/reports'
import { Route as AppAppSettingsRouteImport } from './routes/_app/app/settings'
import { Route as AppAppTransactionsRouteImport } from './routes/_app/app/transactions'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppPlanningRoute = AppAppPlanningRouteImport.update({
  id: '/app/planning',
  path: '/app/planning',
  getParentRoute: () => AppRoute,
} as any)
const AppAppReportsRoute = AppAppReportsRouteImport.update({
  id: '/app/reports',
  path: '/app/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSettingsRoute = AppAppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTransactionsRoute = AppAppTransactionsRouteImport.update({
  id: '/app/transactions',
  path: '/app/transactions',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/planning': typeof AppAppPlanningRoute
  '/app/reports': typeof AppAppReportsRoute
  '/app/settings': typeof AppAppSettingsRoute
  '/app/transactions': typeof AppAppTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AppAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/planning': typeof AppAppPlanningRoute
  '/app/reports': typeof AppAppReportsRoute
  '/app/settings': typeof AppAppSettingsRoute
  '/app/transactions': typeof AppAppTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AppAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/app/planning': typeof AppAppPlanningRoute
  '/_app/app/reports': typeof AppAppReportsRoute
  '/_app/app/settings': typeof AppAppSettingsRoute
  '/_app/app/transactions': typeof AppAppTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/app/': typeof AppAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/login'
    | '/register'
    | '/app/planning'
    | '/app/reports'
    | '/app/settings'
    | '/app/transactions'
    | '/api/auth/$'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/login'
    | '/register'
    | '/app/planning'
    | '/app/reports'
    | '/app/settings'
    | '/app/transactions'
    | '/api/auth/$'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/help'
    | '/login'
    | '/register'
    | '/_app/app/planning'
    | '/_app/app/reports'
    | '/_app/app/settings'
    | '/_app/app/transactions'
    | '/api/auth/$'
    | '/_app/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/planning': {
      id: '/_app/app/planning'
      path: '/app/planning'
      fullPath: '/app/planning'
      preLoaderRoute: typeof AppAppPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/reports': {
      id: '/_app/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppAppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/settings': {
      id: '/_app/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/transactions': {
      id: '/_app/app/transactions'
      path: '/app/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppAppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAppPlanningRoute: typeof AppAppPlanningRoute
  AppAppReportsRoute: typeof AppAppReportsRoute
  AppAppSettingsRoute: typeof AppAppSettingsRoute
  AppAppTransactionsRoute: typeof AppAppTransactionsRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppPlanningRoute: AppAppPlanningRoute,
  AppAppReportsRoute: AppAppReportsRoute,
  AppAppSettingsRoute: AppAppSettingsRoute,
  AppAppTransactionsRoute: AppAppTransactionsRoute,
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
